### ISSUE TITLE
e-mail issue

### ISSUE THREAD

**Issue by jhoms** [basking-in-the-sun2000/solar-logger#17]
I had problems making my GMail account to send messages.

I fixed them by changing this part of the emails.py code:

```
    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(config.mail_server, config.mail_port) as server:
            if config.debug:
                server.set_debuglevel(1)
            server.ehlo()  # Can be omitted
            server.starttls(context=context)
            server.ehlo()  # Can be omitted
            server.login(config.fromaddr, config.mail_pass)
            server.sendmail(config.fromaddr, config.toaddrs, message)
    except Exception as e:
        print("mailing error: %s" % str(e))
```

Hope it helps.

**Comment by basking-in-the-sun2000** [comment]
Never realized that 465 used ssl, and 587 used tls. That is why you were having issues, they aren't compatible. Interesting

Also added some tls version checking, since 1.0 and 1.1 are deprecated. Hope it won't cause issues

Check 7b1af21b2e9946ba5d8218dac5ff63914c7bb013 which should fix your problems
